const express = require("express");
const { nanoid } = require("nanoid");
const { transact, read } = require("./db");
const { requireAuth } = require("./auth-helper");
const { scoreLead } = require("./flows");
const { runAutomationsForEvent } = require("./automations");
const router = express.Router();
function checkAccess(req,businessId,res){if(req.user.role==="client"&&req.user.businessId!==businessId){res.status(403).json({error:"Not allowed"});return false;}return true;}
router.post("/businesses/:businessId/leads",async(req,res)=>{const {businessId}=req.params;const {name,phone,answers={},conversation=[],source="website_chat"}=req.body||{};const biz=read().businesses.find(b=>b.id===businessId);if(!biz)return res.status(404).json({error:"Business not found"});const {score,tier}=scoreLead({...answers,phone});const lead={id:nanoid(10),businessId,name:name||"Unknown",phone:phone||answers.phone||"",answers,conversation:Array.isArray(conversation)?conversation:[],source,score,tier,status:"new",createdAt:new Date().toISOString()};await transact(d=>d.leads.push(lead));await runAutomationsForEvent(businessId,"lead_created",{leadId:lead.id});res.status(201).json({lead});});
router.get("/businesses/:businessId/leads",requireAuth(),(req,res)=>{const {businessId}=req.params;if(!checkAccess(req,businessId,res))return;res.json(read().leads.filter(l=>l.businessId===businessId).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));});
router.patch("/leads/:leadId",requireAuth(),async(req,res)=>{const {status}=req.body||{};const valid=["new","contacted","qualified","won","lost"];if(!valid.includes(status))return res.status(400).json({error:"Invalid status"});const result=await transact(data=>{const lead=data.leads.find(l=>l.id===req.params.leadId);if(!lead)return null;if(req.user.role==="client"&&req.user.businessId!==lead.businessId)return "forbidden";const previousStatus=lead.status;lead.status=status;lead.updatedAt=new Date().toISOString();return {lead,previousStatus};});if(result==="forbidden")return res.status(403).json({error:"Not allowed"});if(!result)return res.status(404).json({error:"Lead not found"});if(result.previousStatus!==result.lead.status)await runAutomationsForEvent(result.lead.businessId,"lead_status_changed",{leadId:result.lead.id});res.json({lead:result.lead});});
router.get("/businesses/:businessId/analytics",requireAuth(),(req,res)=>{const {businessId}=req.params;if(!checkAccess(req,businessId,res))return;const data=read();const leads=data.leads.filter(l=>l.businessId===businessId);const appts=data.appointments.filter(a=>a.businessId===businessId);const byTier={hot:0,warm:0,cold:0};const byStatus={new:0,contacted:0,qualified:0,won:0,lost:0};leads.forEach(l=>{byTier[l.tier]=(byTier[l.tier]||0)+1;byStatus[l.status]=(byStatus[l.status]||0)+1;});res.json({totalLeads:leads.length,byTier,byStatus,totalAppointments:appts.length,conversionRate:leads.length?Math.round(byStatus.won/leads.length*100):0});});
module.exports=router;
