/* Reliable multilingual lead-chat widget: answer-first validation + speech alternatives */
(function () {
  const script = document.currentScript;
  const businessId = script && script.dataset.businessId;
  const API = script ? new URL(script.src, location.href).origin + "/api" : location.origin + "/api";
  if (!businessId || window.__AI_VOICE_WIDGET_LOADED__) return;
  window.__AI_VOICE_WIDGET_LOADED__ = true;

  const style = document.createElement("style");
  style.textContent = `.avw-b{position:fixed;right:22px;bottom:22px;width:60px;height:60px;border:0;border-radius:50%;background:#d9622b;color:#fff;font-size:25px;cursor:pointer;z-index:2147483000;box-shadow:0 10px 28px #0004}.avw{position:fixed;right:22px;bottom:94px;width:min(390px,calc(100vw - 28px));height:min(560px,calc(100vh - 120px));display:none;flex-direction:column;overflow:hidden;border-radius:18px;background:#fff;font:14px Arial,sans-serif;box-shadow:0 20px 60px #0005;z-index:2147483001}.avw.on{display:flex}.avh{padding:16px;background:#161b24;color:#fff;font-weight:700}.avh small{display:block;opacity:.72;font-weight:400;margin-top:4px}.avbody{flex:1;overflow:auto;padding:14px;background:#faf8f5}.avm{max-width:88%;padding:10px 12px;margin-bottom:10px;border-radius:12px;line-height:1.45;white-space:pre-wrap}.bot{background:#fff;border:1px solid #e7e2da;color:#161b24}.usr{margin-left:auto;background:#d9622b;color:#fff}.avr{display:flex;border-top:1px solid #e7e2da}.avr input{flex:1;min-width:0;border:0;padding:14px;font-size:14px;outline:0}.avr button{border:0;background:#d9622b;color:#fff;padding:0 14px;font-weight:700;cursor:pointer}.avr .mic{min-width:48px;font-size:18px}.avr .mic.on{background:#a52b2b}.done{text-align:center;padding:12px;color:#28734d}`;
  document.head.appendChild(style);

  const bubble=document.createElement("button"); bubble.className="avw-b"; bubble.textContent="💬"; document.body.appendChild(bubble);
  const box=document.createElement("div"); box.className="avw";
  box.innerHTML='<div class="avh">Chat with us<small>Tamil / English / Tanglish voice supported</small></div><div class="avbody"></div><div class="avr"><input placeholder="Type or use microphone…"><button class="mic" type="button">🎤</button><button class="send" type="button">Send</button></div>';
  document.body.appendChild(box);
  const body=box.querySelector(".avbody"), input=box.querySelector("input"), mic=box.querySelector(".mic"), send=box.querySelector(".send");
  const state={flow:null,step:0,name:"",answers:{},started:false,phase:"lead",saved:false,conversation:[],appointment:{},appointmentStep:0};

  const add=(text,who="bot")=>{const d=document.createElement("div");d.className=`avm ${who==='bot'?'bot':'usr'}`;d.textContent=String(text||"");body.appendChild(d);body.scrollTop=body.scrollHeight;state.conversation.push({role:who==='bot'?'assistant':'user',text:String(text||"")});};
  const current=()=>state.flow?.questions?.[state.step-1]||null;
  const normalize=v=>String(v||"").normalize("NFC").replace(/[௦-௯]/g,c=>"0123456789"["௦௧௨௩௪௫௬௭௮௯".indexOf(c)]).replace(/\s+/g," ").trim();

  function typeOf(q){const s=`${q?.id||""} ${q?.text||""}`.toLowerCase();if(/phone|mobile|whatsapp|contact|number|போன்|நம்பர்/.test(s))return"phone";if(/budget|price|cost|amount|range|பட்ஜெட்|விலை|செலவு/.test(s))return"budget";if(/bhk|bedroom|room/.test(s))return"bhk";if(/purpose|goal|looking|reason|பயன்பாடு|நோக்கம்/.test(s))return"purpose";if(/date/.test(s))return"date";if(/time/.test(s))return"time";return"text"}
  function digitsFromSpeech(v){let t=normalize(v).toLowerCase();const words={zero:"0",oh:"0",one:"1",two:"2",three:"3",four:"4",five:"5",six:"6",seven:"7",eight:"8",nine:"9",zeroo:"0",ஒன்று:"1",ஒரு:"1",இரண்டு:"2",மூன்று:"3",நான்கு:"4",ஐந்து:"5",ஆறு:"6",ஏழு:"7",எட்டு:"8",ஒன்பது:"9",பூஜ்யம்:"0"};t=t.replace(/[a-z\u0B80-\u0BFF]+/gi,w=>words[w]??w);return t.replace(/\D/g,"")}
  function purpose(v){const t=normalize(v).toLowerCase();if(/own|personal|self|living|சொந்த/.test(t))return"Own Use";if(/invest|rental|rent|income|முதலீடு|வாடகை/.test(t))return"Investment";return""}
  function validate(q,v){const raw=normalize(v), type=typeOf(q);if(!raw)return{ok:false};if(type==="phone"){const d=digitsFromSpeech(raw);return d.length>=10&&d.length<=15?{ok:true,value:d}:{ok:false}}if(type==="purpose"){const p=purpose(raw);return p?{ok:true,value:p}:{ok:false}}if(type==="bhk"){const m=raw.match(/(?:studio|[1-5])\s*(?:bhk|bed(?:room)?s?)?/i);return m?{ok:true,value:/studio/i.test(m[0])?"Studio":`${m[0].match(/[1-5]/)[0]} BHK`}:{ok:false}}if(type==="budget"){const ok=/\d/.test(raw)&&(/₹|\$|rs\b|inr|rupee|lakh|lac|crore|cr|million|thousand|\bk\b|ரூபாய்|லட்சம்|கோடி/i.test(raw)||/^[\d,.]+$/.test(raw));return ok?{ok:true,value:raw}:{ok:false}}if(type==="date"){return /\d|today|tomorrow|today|நாளை|இன்று/i.test(raw)?{ok:true,value:raw}:{ok:false}}if(type==="time"){return /\d|am|pm|morning|afternoon|evening|காலை|மாலை|இரவு/i.test(raw)?{ok:true,value:raw}:{ok:false}}return raw.length>=1?{ok:true,value:raw}:{ok:false}}
  function explicitQuestion(v){const t=normalize(v).toLowerCase();if(/[?？]/.test(t))return true;return /^(what|why|how|when|where|which|who|can|could|would|tell me|enna|ethu|edhu|entha|epdi|eppadi|eppo|enga|evlo|evalo|yen|என்ன|எது|எந்த|எப்படி|எப்போ|எப்போது|எங்கே|எவ்வளவு|ஏன்)\b/i.test(t)}
  function ask(){if(state.step===0){add("First, what's your name?");return}const q=current();if(!q){finishLead();return}add(q.text)}
  async function start(){state.started=true;try{const r=await fetch(`${API}/businesses/${encodeURIComponent(businessId)}/chatbot-flow`);if(!r.ok)throw Error();state.flow=await r.json();add(state.flow.greeting||"Hi! How can I help you?");setTimeout(ask,150)}catch{add("Sorry, chat is temporarily unavailable. Please try again shortly.")}}
  async function save(){if(state.saved)return;try{const r=await fetch(`${API}/businesses/${encodeURIComponent(businessId)}/leads`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:state.name,phone:state.answers.phone||"",answers:state.answers,conversation:state.conversation,source:"website_chat_voice_safe"})});const d=await r.json();if(d.lead){state.saved=true;const x=document.createElement("div");x.className="done";x.textContent="✓ Your details have been saved.";body.appendChild(x)}}catch{}}
  async function finishLead(){if(state.flow?.modulesEnabled?.appointment){state.phase="appointment_offer";add("Would you like to book an appointment? (Yes / No)");return}await finish()}
  async function finish(){if(state.phase==="done")return;state.phase="saving";add("Thank you! Our team will reach out to you shortly. 🙌");await save();state.phase="done";input.disabled=send.disabled=mic.disabled=true;input.placeholder="Conversation complete"}
  async function answerAI(message){try{const q=current();const r=await fetch(`${API}/businesses/${encodeURIComponent(businessId)}/ai-chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,currentQuestion:q?.text||"",currentQuestionId:q?.id||"",answers:state.answers})});const d=await r.json();if(d.answer)add(d.answer);else add("I couldn't answer that right now. Please try again.");if(q)add(`Let's continue: ${q.text}`)}catch{add("I couldn't answer that right now. Please try again.")}}
  async function submit(){let raw=normalize(input.value);if(!raw||state.phase==="done")return;add(raw,"usr");input.value="";
    if(state.phase==="appointment_offer"){if(/^(yes|y|ஆம்|ஆமா|ஆமாங்க)$/i.test(raw)){state.phase="appointment";state.appointmentStep=0;add("What date would you prefer? (DD-MM-YYYY)")}else if(/^(no|n|இல்லை|வேண்டாம்|venam)$/i.test(raw)){await finish()}else add("Please answer Yes or No.");return}
    if(state.phase==="appointment"){if(state.appointmentStep===0){state.appointment.date=raw;state.appointmentStep=1;add("What time would you prefer?");return}if(state.appointmentStep===1){state.appointment.time=raw;state.appointmentStep=2;add("Any note for the team? (Optional — type No if none)");return}state.appointment.notes=raw;try{await fetch(`${API}/businesses/${encodeURIComponent(businessId)}/appointments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(state.appointment)})}catch{}add(`Appointment request saved for ${state.appointment.date} at ${state.appointment.time}.`);await finish();return}
    if(state.step===0){if(explicitQuestion(raw)){await answerAI(raw);return}state.name=raw;state.step=1;ask();return}
    const q=current(), checked=validate(q,raw);
    // Critical ordering: a valid field answer always wins over AI question detection.
    if(checked.ok){state.answers[q.id]=checked.value;state.step++;ask();return}
    if(explicitQuestion(raw)){await answerAI(raw);return}
    const t=typeOf(q);const help={phone:"Please enter a valid phone number (10–15 digits).",budget:"Please enter the budget clearly, for example ₹50 lakh or 1 crore.",bhk:"Please enter Studio, 1 BHK, 2 BHK or 3 BHK.",purpose:"Please answer Own Use or Investment."};add(help[t]||"I didn't catch that. Please repeat your answer.");}

  bubble.onclick=()=>{box.classList.toggle("on");if(box.classList.contains("on")&&!state.started)start();if(box.classList.contains("on"))setTimeout(()=>input.focus(),50)};window.AIWidgetOpen=()=>{box.classList.add("on");if(!state.started)start()};window.AIWidgetClose=()=>box.classList.remove("on");send.onclick=submit;input.addEventListener("keydown",e=>{if(e.key==="Enter")submit()});

  let rec;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){rec=new SR();rec.lang="ta-IN";rec.continuous=false;rec.interimResults=false;rec.maxAlternatives=5;rec.onstart=()=>mic.classList.add("on");rec.onend=()=>mic.classList.remove("on");rec.onerror=()=>mic.classList.remove("on");rec.onresult=e=>{const alts=[];for(let i=e.resultIndex;i<e.results.length;i++)for(let j=0;j<e.results[i].length;j++)alts.push(e.results[i][j].transcript);const q=state.step===0?null:current();let best=alts[0]||"";if(q){let bestScore=-1;for(const a of alts){const v=validate(q,a);let score=(v.ok?100:0)+a.length/100;if(typeOf(q)==="phone")score+=(digitsFromSpeech(a).length===10?50:0);if(score>bestScore){bestScore=score;best=a}}}input.value=normalize(best);input.focus()};mic.onclick=()=>{try{rec.start()}catch{}}}else{mic.disabled=true;mic.title="Voice input is not supported in this browser"}
})();
